-- =====================================================================
-- Project Topics Validation System - Full Reconstructed Schema
-- Generated by tracing every *.sql dump and *.php migration/setup
-- script in the project root, in the order they were actually applied,
-- and cross-checking each result against how the live application code
-- (controllers under student/, supervisor/, hod/, department_project_coordinator/,
-- faculty_project_coordinator/, super_admin/, library/, external_examiner/)
-- actually reads/writes each table today.
--
-- Sources merged (chronological):
--   1. my_project_topics2 (15).sql   - phpMyAdmin structure dump, 2026-02-17
--                                      (most complete baseline snapshot: 21 tables)
--   2. add_max_students_column.php, migrate_panel_types*.php, setup_*.php,
--      create_schedule_table.php, migrate_chapters.php, update_roles.php,
--      create_hod_module.php / create_fpc_manage_hod.php
--                                      - all already reflected in the dump above,
--                                        or superseded by a later script (kept for
--                                        provenance only, not re-applied here)
--   3. update_hod_schema.php           - added 'hod' to users.role enum
--   4. database_updates.sql            - report_schedules, student_report_overrides
--   5. update_allocation_schema.php    - supervisor_allocation_status
--   6. update_panel_schema.php         - defense_panels.venue/panel_date/panel_time
--   7. clearance_migration.sql (+ run_migration.php)
--                                      - chapter_approvals.chapter_number -> clearance_level
--   8. Databas.sql / update_source_code_schema.php
--                                      - project_topics.source_code_* columns,
--                                        system_settings defaults
--   9. install_evaluation_module.php / sql/evaluation_module.sql
--                                      - users.evaluation_* flags, evaluations,
--                                        evaluation_responses
--  10. install_session_scoping.php (this session)
--                                      - students.session + a per-session unique
--                                        key on (reg_no, session), so switching
--                                        the active session actually isolates
--                                        registrations/topics/allocations instead
--                                        of showing every session's data mixed
--                                        together
--
-- Note on update_sessions.php: an old, abandoned one-off script that tried to add
-- `session` columns to students/supervision/defense_panels/report_schedules/
-- submission_schedules directly (no controller ever read/wrote them, and its
-- defense_panels statement targeted a `defense_date` column that never existed).
-- Superseded by install_session_scoping.php above, which takes a different,
-- narrower approach: only `students.session` is added, and every other table is
-- scoped by joining through it rather than duplicating the column everywhere.
--
-- Column types/FKs reflect the ACTUAL live schema, including its existing quirks
-- (e.g. project_topics.student_id and supervisors.department are VARCHAR, not
-- INT, even though every query treats them as numeric IDs) - nothing here has
-- been "corrected", only reconciled and made re-runnable.
-- =====================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------
-- faculty
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculty` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `faculty` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- departments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `departments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `faculty_id` INT(11) NOT NULL,
  `department_name` VARCHAR(100) NOT NULL,
  `project_guideline` VARCHAR(255) DEFAULT NULL,
  `num_chapters` INT(11) DEFAULT 5,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- system_settings  (global key/value config + current academic session)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_settings` (
  `setting_key` VARCHAR(50) NOT NULL,
  `setting_value` TEXT DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO `system_settings` (`setting_key`, `setting_value`, `description`) VALUES
('current_session', '2025/2026', 'The active academic session for calculations and submissions'),
('max_proposals_per_student', '3', 'Limit on number of topics a student can submit'),
('allow_student_topic_edit', '1', '1 to allow editing pending topics, 0 to lock them'),
('system_announcement', '', 'Global message displayed on user dashboards'),
('similarity_threshold', '30', 'Auto-warning percentage for topic similarity check');

-- ---------------------------------------------------------------------
-- users  (single accounts table for every role: stu/sup/dpc/fpc/hod/admin/lib/ext)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('stu','dpc','fpc','sup','admin','lib','ext','hod') NOT NULL,
  `name` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(100) DEFAULT NULL,
  `faculty_id` INT(11) DEFAULT NULL,
  `department` VARCHAR(100) DEFAULT NULL,
  `title` VARCHAR(50) DEFAULT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  `first_login` DATETIME DEFAULT NULL,
  `password_changed` VARCHAR(50) DEFAULT NULL,
  `session` VARCHAR(255) DEFAULT NULL COMMENT 'current PHP session id while logged in',
  `evaluation_due` TINYINT(1) NOT NULL DEFAULT 0,
  `evaluation_submitted` TINYINT(1) NOT NULL DEFAULT 0,
  `evaluation_remind_count` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- students  (id shares the same PK value as the matching `users` row)
-- `session` is the source of truth for session-scoping: every downstream
-- table that references student_id (project_topics, supervision,
-- chapter_approvals, defense_scores, student_panel_assignments,
-- supervisor_assessments) is scoped for free by joining through this
-- column, rather than duplicating a session column on each of them. A
-- repeating student gets a brand new row in the new session - that's why
-- reg_no is only unique per-session, not globally.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `students` (
  `id` INT(11) NOT NULL,
  `reg_no` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `faculty_id` INT(11) DEFAULT NULL,
  `department` INT(11) NOT NULL,
  `session` VARCHAR(50) NOT NULL,
  `first_login` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reg_no_session` (`reg_no`, `session`),
  CONSTRAINT `fk_students_user` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- supervisors  (id shares the same PK value as the matching `users` row)
-- Note: `department` is VARCHAR in the live DB, storing a departments.id value
-- as text - kept as-is to match production rather than "corrected" to INT.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `supervisors` (
  `id` INT(11) NOT NULL,
  `staff_no` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) DEFAULT NULL,
  `phone` VARCHAR(20) DEFAULT NULL,
  `faculty_id` INT(11) DEFAULT NULL,
  `department` VARCHAR(100) NOT NULL,
  `max_students` INT(11) NOT NULL DEFAULT 10,
  `current_load` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `staff_no` (`staff_no`),
  CONSTRAINT `fk_supervisors_user` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- external_examiners  (id shares the same PK value as the matching `users` row)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `external_examiners` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) DEFAULT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `affiliation` VARCHAR(255) DEFAULT NULL,
  `department_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `external_examiners_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- project_topics
-- Note: `student_id` is VARCHAR in the live DB (holds a students.id value as
-- text); kept as-is rather than "corrected" to INT.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_topics` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(255) NOT NULL,
  `student_id` VARCHAR(50) NOT NULL,
  `student_name` VARCHAR(100) DEFAULT NULL,
  `session` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) DEFAULT 'pending',
  `pdf_path` VARCHAR(255) DEFAULT NULL,
  `report_status` ENUM('pending','approved','rejected','not_submitted') DEFAULT 'not_submitted',
  `report_feedback` TEXT DEFAULT NULL,
  `source_code_path` VARCHAR(255) DEFAULT NULL,
  `source_code_status` ENUM('not_submitted','pending','approved','rejected') DEFAULT 'not_submitted',
  `source_code_feedback` TEXT DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- past_projects  (historical/archive records used for similarity checks)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `past_projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `faculty_id` INT(11) NOT NULL,
  `topic` VARCHAR(255) NOT NULL,
  `reg_no` VARCHAR(50) NOT NULL,
  `student_name` VARCHAR(100) NOT NULL,
  `session` VARCHAR(20) NOT NULL,
  `supervisor_name` VARCHAR(50) NOT NULL,
  `pdf_path` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- supervision  (active supervisor <-> student allocation)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `supervision` (
  `allocation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `supervisor_id` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  `allocation_date` DATETIME NOT NULL,
  `status` VARCHAR(20) DEFAULT 'active',
  PRIMARY KEY (`allocation_id`),
  KEY `supervisor_id` (`supervisor_id`),
  KEY `student_id` (`student_id`),
  CONSTRAINT `supervision_ibfk_1` FOREIGN KEY (`supervisor_id`) REFERENCES `supervisors` (`id`),
  CONSTRAINT `supervision_ibfk_2` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- supervisor_allocation_status  (tracks a supervisor accepting their load for a session)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `supervisor_allocation_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `supervisor_id` INT(11) NOT NULL,
  `session` VARCHAR(100) NOT NULL,
  `accepted_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_supervisor_session` (`supervisor_id`, `session`),
  CONSTRAINT `fk_allocation_status_supervisor` FOREIGN KEY (`supervisor_id`) REFERENCES `supervisors` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- supervisor_assessments  (supervisor's progress/effort score for their student)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `supervisor_assessments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `supervisor_id` INT(11) NOT NULL,
  `score` DECIMAL(5,2) DEFAULT NULL,
  `comments` TEXT DEFAULT NULL,
  `academic_session` VARCHAR(20) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_sup_session` (`student_id`, `supervisor_id`, `academic_session`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- defense_panels
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `defense_panels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `panel_name` VARCHAR(100) NOT NULL,
  `panel_type` ENUM('proposal','internal','external') DEFAULT 'proposal',
  `department_id` INT(11) NOT NULL,
  `max_students` INT(11) DEFAULT 10,
  `venue` VARCHAR(255) DEFAULT NULL,
  `panel_date` DATE DEFAULT NULL,
  `panel_time` TIME DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- panel_members  (supervisors sitting on a defense panel)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `panel_members` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `panel_id` INT(11) NOT NULL,
  `supervisor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `panel_id` (`panel_id`),
  CONSTRAINT `panel_members_ibfk_1` FOREIGN KEY (`panel_id`) REFERENCES `defense_panels` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- student_panel_assignments  (which panel/stage a student is scheduled for)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_panel_assignments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `panel_id` INT(11) NOT NULL,
  `panel_type` ENUM('proposal','internal','external') NOT NULL DEFAULT 'proposal',
  `academic_session` VARCHAR(20) DEFAULT NULL,
  `assigned_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_student_panel_type` (`student_id`, `academic_session`, `panel_type`),
  KEY `panel_id` (`panel_id`),
  CONSTRAINT `student_panel_assignments_ibfk_1` FOREIGN KEY (`panel_id`) REFERENCES `defense_panels` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- defense_scores  (grades given by a supervisor/external examiner on a panel)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `defense_scores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `supervisor_id` INT(11) NOT NULL COMMENT 'a users.id - may be role sup or ext',
  `panel_id` INT(11) NOT NULL,
  `score` DECIMAL(5,2) DEFAULT NULL,
  `comments` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_sup_panel` (`student_id`, `supervisor_id`, `panel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- chapter_approvals  (per-clearance-stage sign-off: proposal/internal/external)
-- Originally keyed by an integer chapter_number; clearance_migration.sql
-- (2026-07-01) replaced that with the clearance_level string used today.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `chapter_approvals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `supervisor_id` INT(11) NOT NULL,
  `clearance_level` VARCHAR(50) NOT NULL COMMENT 'proposal | internal | external',
  `status` ENUM('pending','approved') DEFAULT 'pending',
  `approval_date` DATETIME DEFAULT NULL,
  `academic_session` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_clearance` (`student_id`, `clearance_level`),
  CONSTRAINT `fk_chapter_student` FOREIGN KEY (`student_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_chapter_supervisor` FOREIGN KEY (`supervisor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- submission_schedules  (per-department window for topic submission)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `submission_schedules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `department_id` INT(11) DEFAULT NULL,
  `submission_start` DATETIME DEFAULT NULL,
  `submission_end` DATETIME DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `department_id` (`department_id`),
  CONSTRAINT `submission_schedules_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- report_schedules  (per-department window for final report submission)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `report_schedules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `department_id` INT(11) DEFAULT NULL,
  `submission_start` DATETIME DEFAULT NULL,
  `submission_end` DATETIME DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `department_id` (`department_id`),
  CONSTRAINT `report_schedules_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- student_report_overrides  (per-student exception to the report_schedules window)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_report_overrides` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `submission_start` DATETIME NOT NULL,
  `submission_end` DATETIME NOT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_id` (`student_id`),
  CONSTRAINT `student_report_overrides_ibfk_1` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- student_submission_overrides  (per-student exception to the submission_schedules window)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_submission_overrides` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `submission_start` DATETIME NOT NULL,
  `submission_end` DATETIME NOT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_id` (`student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- feedback  (system-generated notices to a student, by reg_no)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_reg_no` VARCHAR(50) NOT NULL,
  `message` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- messages  (in-app user-to-user messaging, powers the header unread badge)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sender_id` INT(11) NOT NULL,
  `receiver_id` INT(11) NOT NULL,
  `subject` VARCHAR(255) DEFAULT NULL,
  `message_text` TEXT NOT NULL,
  `is_read` TINYINT(1) DEFAULT 0,
  `sent_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `academic_session` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sender` (`sender_id`),
  KEY `fk_receiver` (`receiver_id`),
  CONSTRAINT `fk_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------
-- library_temp_access  (one-time passcodes for guest library catalog access)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_temp_access` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `passcode` VARCHAR(50) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_used` TINYINT(1) DEFAULT 0,
  `used_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- =====================================================================
-- System Evaluation module (added this session - see sql/evaluation_module.sql
-- for this part on its own, and install_evaluation_module.php to apply just
-- this part idempotently on a live server)
-- =====================================================================

CREATE TABLE IF NOT EXISTS `evaluations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `respondent_role` VARCHAR(20) NOT NULL COMMENT 'system role at time of submission: stu/sup/dpc/fpc/hod',
  `role` VARCHAR(20) NOT NULL COMMENT 'questionnaire type: student/supervisor/coordinator',
  `questionnaire_version` VARCHAR(30) NOT NULL,
  `department_id` INT(11) DEFAULT NULL,
  `department_name` VARCHAR(150) DEFAULT NULL,
  `faculty_id` INT(11) DEFAULT NULL,
  `faculty_name` VARCHAR(150) DEFAULT NULL,
  `academic_session` VARCHAR(20) DEFAULT NULL,
  `submitted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_questionnaire` (`user_id`, `questionnaire_version`),
  KEY `idx_role` (`role`),
  KEY `idx_department` (`department_id`),
  KEY `idx_faculty` (`faculty_id`),
  CONSTRAINT `fk_evaluations_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `evaluation_responses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `evaluation_id` INT(11) NOT NULL,
  `section` VARCHAR(150) NOT NULL,
  `question_no` VARCHAR(10) NOT NULL,
  `question_text` TEXT NOT NULL,
  `answer_value` TINYINT(1) DEFAULT NULL COMMENT '1-5 Likert scale',
  `answer_text` TEXT DEFAULT NULL COMMENT 'open-ended / single-choice answer',
  PRIMARY KEY (`id`),
  KEY `idx_evaluation` (`evaluation_id`),
  CONSTRAINT `fk_responses_evaluation` FOREIGN KEY (`evaluation_id`) REFERENCES `evaluations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;
